# .github/workflows/cloudflare.yml
name: Deploy worker
on:
  push:
    branches: [ main ]
    paths: [ 'worker/**', '.github/workflows/cloudflare.yml' ]

permissions:
  contents: read

concurrency:
  group: worker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: worker
          command: deploy