name: Deploy web to Pages
on:
  push:
    branches: [ main ]
    paths: [ 'web/**', '.github/workflows/pages.yml' ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with: { path: web }
      - uses: actions/deploy-pages@v4